// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/station.proto

package stationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_proto_station_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{0}
}

func (x *GetInventoryRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	FuelStock     map[string]float32     `protobuf:"bytes,2,rep,name=fuel_stock,json=fuelStock,proto3" json:"fuel_stock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // e.g., "petrol": 5000.5, "diesel": 8000.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_proto_station_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{1}
}

func (x *GetInventoryResponse) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *GetInventoryResponse) GetFuelStock() map[string]float32 {
	if x != nil {
		return x.FuelStock
	}
	return nil
}

type DeductFuelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	FuelType      string                 `protobuf:"bytes,2,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Amount        float32                `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductFuelRequest) Reset() {
	*x = DeductFuelRequest{}
	mi := &file_proto_station_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductFuelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductFuelRequest) ProtoMessage() {}

func (x *DeductFuelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductFuelRequest.ProtoReflect.Descriptor instead.
func (*DeductFuelRequest) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{2}
}

func (x *DeductFuelRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *DeductFuelRequest) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *DeductFuelRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DeductFuelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductFuelResponse) Reset() {
	*x = DeductFuelResponse{}
	mi := &file_proto_station_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductFuelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductFuelResponse) ProtoMessage() {}

func (x *DeductFuelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductFuelResponse.ProtoReflect.Descriptor instead.
func (*DeductFuelResponse) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{3}
}

func (x *DeductFuelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductFuelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_station_proto protoreflect.FileDescriptor

const file_proto_station_proto_rawDesc = "" +
	"\n" +
	"\x13proto/station.proto\x12\astation\"4\n" +
	"\x13GetInventoryRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\"\xc0\x01\n" +
	"\x14GetInventoryResponse\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12K\n" +
	"\n" +
	"fuel_stock\x18\x02 \x03(\v2,.station.GetInventoryResponse.FuelStockEntryR\tfuelStock\x1a<\n" +
	"\x0eFuelStockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"g\n" +
	"\x11DeductFuelRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x1b\n" +
	"\tfuel_type\x18\x02 \x01(\tR\bfuelType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x02R\x06amount\"H\n" +
	"\x12DeductFuelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa4\x01\n" +
	"\x0eStationService\x12K\n" +
	"\fGetInventory\x12\x1c.station.GetInventoryRequest\x1a\x1d.station.GetInventoryResponse\x12E\n" +
	"\n" +
	"DeductFuel\x12\x1a.station.DeductFuelRequest\x1a\x1b.station.DeductFuelResponseB\x13Z\x11./proto/stationpbb\x06proto3"

var (
	file_proto_station_proto_rawDescOnce sync.Once
	file_proto_station_proto_rawDescData []byte
)

func file_proto_station_proto_rawDescGZIP() []byte {
	file_proto_station_proto_rawDescOnce.Do(func() {
		file_proto_station_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_station_proto_rawDesc), len(file_proto_station_proto_rawDesc)))
	})
	return file_proto_station_proto_rawDescData
}

var file_proto_station_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_station_proto_goTypes = []any{
	(*GetInventoryRequest)(nil),  // 0: station.GetInventoryRequest
	(*GetInventoryResponse)(nil), // 1: station.GetInventoryResponse
	(*DeductFuelRequest)(nil),    // 2: station.DeductFuelRequest
	(*DeductFuelResponse)(nil),   // 3: station.DeductFuelResponse
	nil,                          // 4: station.GetInventoryResponse.FuelStockEntry
}
var file_proto_station_proto_depIdxs = []int32{
	4, // 0: station.GetInventoryResponse.fuel_stock:type_name -> station.GetInventoryResponse.FuelStockEntry
	0, // 1: station.StationService.GetInventory:input_type -> station.GetInventoryRequest
	2, // 2: station.StationService.DeductFuel:input_type -> station.DeductFuelRequest
	1, // 3: station.StationService.GetInventory:output_type -> station.GetInventoryResponse
	3, // 4: station.StationService.DeductFuel:output_type -> station.DeductFuelResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_station_proto_init() }
func file_proto_station_proto_init() {
	if File_proto_station_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_station_proto_rawDesc), len(file_proto_station_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_station_proto_goTypes,
		DependencyIndexes: file_proto_station_proto_depIdxs,
		MessageInfos:      file_proto_station_proto_msgTypes,
	}.Build()
	File_proto_station_proto = out.File
	file_proto_station_proto_goTypes = nil
	file_proto_station_proto_depIdxs = nil
}
