syntax = "proto3";
 
package order;
option go_package = "./proto/orderpb";
 
service OrderService {
  rpc PlaceOrder (PlaceOrderRequest) returns (PlaceOrderResponse);
  rpc GetOrder (GetOrderRequest) returns (GetOrderResponse);
}
 
message PlaceOrderRequest {
  string user_id = 1;
  string station_id = 2;
  string fuel_type = 3;
  float amount = 4;
}
 
message PlaceOrderResponse {
  string order_id = 1;
  string status = 2;
  string message = 3;
}

message GetOrderRequest {
  string order_id = 1;
  string user_id = 2;
  string role = 3;
}

message GetOrderResponse {
  string order_id = 1;
  string user_id = 2;
  string station_id = 3;
  string fuel_type = 4;
  float amount = 5;
  string status = 6; // e.g., "pending", "completed", "failed"
}

